const data_base = [ 
    {
        nome:"Renato da silva",
        cargo:"Facilitador",
        empresa:"Kenzie Academy",
        image:"./img/img.jpg",
        modulo: "M1",
        status: true,
    },
    // {
    //     nome:"João Roberto",
    //     cargo:"Facilitador",
    //     empresa:"Kenzie Academy",
    //     image:"face.png",
    //     modulo: "M1",
    //     status: false,
    // },
    // {
    //     nome:"Renata da Silva",
    //     cargo:"Facilitador",
    //     empresa:"Kenzie Academy",
    //     image:"face1.jpeg",
    //     modulo: "M2",
    //     status: true,
    // },
    // {
    //     nome:"Bruno",
    //     cargo:"Facilitador",
    //     empresa:"Kenzie Academy",
    //     image:"face2.jpeg",
    //     modulo: "M3",
    //     status: false,
    // },
    // {
    //     nome:"Mariana",
    //     cargo:"Facilitador",
    //     empresa:"Kenzie Academy",
    //     image:"face3.jpeg",
    //     modulo: "M4",
    //     status: false,
    // },
    // {
    //     nome:"Ana Maria",
    //     cargo:"Facilitador - M2",
    //     empresa:"Kenzie Academy",
    //     image:"face4.jpg",
    //     modulo: "M2",
    //     status: true,
    // },
    // {
    //     nome:"Natalia",
    //     cargo:"Facilitador - M2",
    //     empresa:"Kenzie Academy",
    //     image:"face5.jpeg",
    //     modulo: "M2",
    //     status: true,
    // },
    // {
    //     nome:"Caio",
    //     cargo:"Facilitador - M2",
    //     empresa:"Kenzie Academy",
    //     image:"face5.jpg",
    //     modulo: "M2",
    //     status: false,
    // },
    // {
    //     nome:"Renata da Silva",
    //     cargo:"Facilitador",
    //     empresa:"Kenzie Academy",
    //     image:"face1.jpeg",
    //     modulo: "M2",
    //     status: true,
    // },
    // {
    //     nome:"Bruno",
    //     cargo:"Facilitador",
    //     empresa:"Kenzie Academy",
    //     image:"face2.jpeg",
    //     modulo: "M3",
    //     status: false,
    // },
    // {
    //     nome:"Mariana",
    //     cargo:"Facilitador",
    //     empresa:"Kenzie Academy",
    //     image:"face3.jpeg",
    //     modulo: "M4",
    //     status: false,
    // },
    // {
    //     nome:"Ana Maria",
    //     cargo:"Facilitador - M2",
    //     empresa:"Kenzie Academy",
    //     image:"face4.jpg",
    //     modulo: "M2",
    //     status: true,
    // },
    // {
    //     nome:"Natalia",
    //     cargo:"Facilitador - M2",
    //     empresa:"Kenzie Academy",
    //     image:"face5.jpeg",
    //     modulo: "M2",
    //     status: true,
    // },
    // {
    //     nome:"Caio",
    //     cargo:"Facilitador - M2",
    //     empresa:"Kenzie Academy",
    //     image:"face5.jpg",
    //     modulo: "M2",
    //     status: false,
    // },
]